config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  authenticated :user do
    root :to => "dashboard#show", as: :authenticated_root
  end

  root :to => 'registration#show', id: 'profile'

  resources :specialities do
    resources :download_programs
    resources :programs do
      resource :bookmark
      resource :note
    end
  end

  resource :contact
  resources :registration
  resources :users

  get '/sitemap.xml', to: 'sitemap#show'
end

app/models/program.rb
require 'csv'

class Program < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :speciality
  has_many :program_users
  has_many :users, through: :program_users
  has_many :medical_school_programs
  has_many :medical_schools, through: :medical_school_programs
  scope :active, -> { where(active: 1) }

  validates_presence_of :acgme_program_code, :name
  validates_inclusion_of :minimum_step_1_score, in: 0..300, message: I18n.t(:invalid_score_error)
  validates_inclusion_of :minimum_step_2_score, in: 0..300, allow_nil: true,
                                                message: I18n.t(:invalid_score_error)

  def bookmarked?(user)
    program_users.select { |pu| pu.program == self && pu.user == user && pu.bookmark == true }.present?
  end

  def percentage(type)
    return send(type) unless medical_schools.present?

    medical_school_ids = medical_schools
                         .select { |medical_school| medical_school.img_type == type }
                         .pluck(:id)

    type_sum = medical_school_programs
               .select { |medical_school_program| medical_school_ids.include? medical_school_program.medical_school_id }
               .pluck(:percentage).sum

    total_sum = medical_school_programs.to_a.pluck(:percentage).sum

    (type_sum.fdiv(total_sum) * 100).round
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  include ProgramConcern

  before_action :redirect_old_url, only: [:show]
  load_and_authorize_resource :speciality, find_by: :slug
  load_and_authorize_resource :program, through: :speciality, find_by: :slug
  layout :resolve_layout
  before_action :find_or_initialize_program_user, only: :show
  skip_before_action :authenticate_user, only: :show

  def show
    ahoy.track("Viewing program: #{@program.name} (#{@program.speciality.name})")

    @form = CreateProgramNoteForm.new program_user: @program_user
    @program = @program.decorate

    render layout: current_user.nil? ? 'program' : 'application'
  end

  def index
    ahoy.track("Viewing speciality list: #{@speciality.name}")

    @programs = @programs.decorate.includes(:program_users, :users, :medical_schools)
    @matching_programs = if params['all'] == 'true' || params['img'] == 'true'
                           @programs.order(:name)
                         else
                           matching_programs
                         end

    @matching_program_count = @matching_programs.count
    @matching_programs = @matching_programs.first(5) unless current_user.paid?

    bookmark_count = ProgramUser.where(program: @matching_programs, user: current_user, bookmark: true).count
    @fee = calculate_fee(bookmark_count)
  end

  def edit
    @form = EditProgramForm.new program: @program
  end

  def update
    @form = edit_form

    if @form.submit
      flash.notice = 'Program edited successfully'
      next_program = @program.speciality.programs.where("#{current_user.img_type} > ?", 0).order(:name).where(
        'name > ?', @program.name
      ).first
      redirect_to edit_speciality_program_path(@speciality, next_program)
    else
      render 'edit'
    end
  end

  private

  def resolve_layout
    'devise' if current_user.nil?
  end

  def edit_form
    form_params = params.require(:edit_program_form).permit(EditProgramForm.accessible_attributes)
    EditProgramForm.new form_params.merge(program: @program)
  end

  def calculate_fee(bookmark_count)
    if bookmark_count.between?(1, 10)
      99
    elsif bookmark_count.between?(11, 20)
      16 * bookmark_count
    elsif bookmark_count.between?(21, 30)
      20 * bookmark_count
    elsif bookmark_count >= 31
      26 * bookmark_count
    else
      0
    end
  end

  def find_or_initialize_program_user
    @program_user = ProgramUser.find_or_initialize_by(program: @program, user: current_user)
  end

  def redirect_old_url
    @speciality = Speciality.friendly.find(params[:speciality_id])
    return if @speciality.friendly_id == params[:speciality_id]

    @program = Program.find_by(slug: params[:id], speciality: @speciality)

    redirect_to speciality_program_path(@speciality, @program), status: 301
  end
end

app/views/programs/edit.html.erb
<div class="header">
  <h4 class="card-title font-weight-bold">
    <%= @program.name %>
  </h4>

  Program ID:
  <div id="textToCopy" class="d-inline-block">
    <%= @program.acgme_program_code %>
  </div>
  <div onclick="copyClipboard()" class="text-primary d-inline-block">[Copy]</div><br/>

  Website: <%= link_to(@program.website, @program.website, target: :_blank) %>
</div>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" onclick="showTab(this.id)" id="js-program-tab">Details</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" onclick="showTab(this.id)" id="js-program-visa-tab">Visa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" onclick="showTab(this.id)" id="js-program-contact-tab">Contact</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" onclick="showTab(this.id)" id="js-program-statistics-tab">Statistics</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" onclick="showTab(this.id)" id="js-program-misc-tab">Misc</a>
  </li>
</ul>

<div class="row">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-body mt-3">
        <div class="row">
          <div class="col-md-12">

            <%= bootstrap_form_for @form, :url => speciality_program_url(@speciality, @program), label_col: 'col-sm-3', method: :put do |f| %>

              <div id="js-program">
                <div class="field">
                  <%= f.text_field :minimum_step_1_score %>
                </div>

                <div class="field">
                  <%= f.select :step_2_required, [['Yes'], ['No']], include_blank: true %>
                </div>

                <div class="field">
                  <%= f.text_field :minimum_step_2_score %>
                </div>

                <div class="field">
                  <%= f.text_field :must_pass_step_2_cs_first_attempt %>
                </div>

                <div class="field">
                  <%= f.select :us_clinical_experience, [['Yes', true], ['No', false]], include_blank: true %>
                </div>

                <div class="field">
                  <%= f.select :years_since_graduation, options_for_select(0..10, :selected => @form.years_since_graduation), include_blank: true %>
                </div>
              </div>

              <div id="js-program-visa" class="d-none">
                <div class="field">
                  <%= f.select :j_1_sponsorship_through_ecfmg, [['Yes'], ['No']], include_blank: true %>
                </div>

                <div class="field">
                  <%= f.select :h1_b, [['Yes'], ['No']], include_blank: true %>
                </div>
              </div>

              <div id="js-program-contact" class="d-none">
                <div class="field">
                  <%= f.text_field :website %>
                </div>

                <div class="field">
                  <%= f.text_field :phone %>
                </div>

                <div class="field">
                  <%= f.text_field :email %>
                </div>

                <div class="field">
                  <%= f.text_field :program_coordinator %>
                </div>

                <div class="field">
                  <%= f.text_field :program_coordinator_email %>
                </div>

                <div class="field">
                  <%= f.text_field :program_director %>
                </div>
              </div>

              <div id="js-program-statistics" class="d-none">
                <div class="field">
                  <%= f.text_field :us_md_graduates %>
                </div>

                <div class="field">
                  <%= f.text_field :us_do_graduates %>
                </div>

                <div class="field">
                  <%= f.text_field :non_us_citizen_international_medical_graduates %>
                </div>

                <div class="field">
                  <%= f.text_field :us_citizen_international_medical_graduates %>
                </div>
              </div>

              <div id="js-program-misc" class="d-none">
                <div class="field">
                  <%= f.text_field :name %>
                </div>

                <div class="field">
                  <%= f.text_field :acgme_program_code %>
                </div>

                <div class="field">
                  <%= f.text_area :notes %>
                </div>

                <div class="field">
                  <%= f.text_field :speciality_id %>
                </div>

                <div class="field">
                  <%= f.text_field :active %>
                </div>
              </div>

              <div class="actions">
                <%= f.submit t(:save), class: 'btn btn-success' %>
                <%= link_to t(:back), speciality_programs_path(@speciality, all: true), class: 'btn btn-info' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-footer ">
        <div class="stats text-right">
          <i class="fa fa-history"></i> Updated <%= @program.updated_at.strftime("%B %d, %Y") %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/index.html.erb
<div class="row">
  <div class="col-lg-12 col-md-6 col-sm-12">
    <div class="card">
      <div class="card-header d-flex">
        <div class="float-left">
          <h4 class="card-title font-weight-bold">
            <%= @speciality.name %> (<%= @matching_program_count %> Matches)
          </h4>
          <p>
            <i class="nc-icon nc-money-coins text-success mr-2"></i>
            <%= t(:eras_application_fees) %> <%= number_to_currency @fee %>
          </p>
        </div>

        <div class="ml-auto align-self-center">
          <% if current_user.paid? %>
            <%= link_to speciality_download_programs_path(@speciality, format: 'csv') do %>
              <button type="button" class="btn btn-success"><%= t(:download_csv) %></button>
            <% end %>
          <% else %>
            <%= link_to checkout_create_path, method: :post, remote: true do %>
              <button type="button" class="btn btn-success"><%= t(:download_csv) %></button>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="card-body ">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th><%= t(:friendliness_score) %></th>
                  <% if current_user.admin? %>
                    <th><%= t(:actions) %></th>
                  <% end %>
                  <th><%= t(:program_name) %></th>
                  <th><%= t(:location) %></th>
                  <th><%= t(:program_code) %></th>
                  <th><%= t(:bookmark) %></th>
                </tr>
              </thead>
              <tbody>
                <% @matching_programs.each do |program| %>
                  <tr>
                    <td>
                      <%= program.send("#{current_user.img_type}_friendliness_score") %>
                    </td>
                    <% if current_user.admin? %>
                      <td>
                        <%= link_to t(:edit), edit_speciality_program_path(@speciality, program) %>
                      </td>
                    <% end %>
                    <td><%= link_to program.name, speciality_program_path(@speciality, program) %></td>
                    <td><%= program.address.split[-3..-2].join(' ') %></td>
                    <td><%= program.acgme_program_code %></td>
                    <td class="text-center">
                      <span class="icon-holder">
                        <%= link_to speciality_program_bookmark_url(@speciality, program), method: :post do %>
                          <% if program.bookmarked?(current_user) %>
                            <%= bootstrap_icon "bookmark-check-fill", fill: "#17a2b8" %>
                          <% else %>
                            <%= bootstrap_icon "bookmark", fill: "gray" %>
                          <% end %>
                        <% end %>
                      </span>
                    </td>
                  </tr>
                <% end %>

                <% unless current_user.paid? %>
                    <tr>
                      <td colspan="6" class="text-center">
                        <%= link_to checkout_create_path, class: 'text-decoration-none', method: :post, remote: true do %>
                          <h4 class="text-danger"><%= t(:upgrade_message) %></h4>
                        <% end %>
                      </td>
                    </tr>
                  <% (@matching_program_count - 5).times do %>
                    <tr>
                      <td class="blurry-text">
                        50
                      </td>
                      <td class="blurry-text"><%= link_to 'The Program Name Has Been Hidden', checkout_create_path, method: :post, remote: true %></td>
                      <td class="blurry-text">Hidden Location</td>
                      <td class="blurry-text">HIDDEN</td>
                      <td class="text-center">
                        <span class="icon-holder">
                          <%= bootstrap_icon "bookmark", fill: "gray" %>
                        </span>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/show.html.erb
<div id="js-placeholder"></div>

<div class="row">
  <div class="col-md-8">
    <div class="card ">
      <div class="card-header ">
        <h4 class="card-title font-weight-bold"><%= @program.name %></h4>
        <%= link_to "https://www.google.com/maps?q=#{@program.address.gsub("\n", ' ')}", class: 'text-decoration-none', target: '_blank' do %>
          <%= image_tag('google_maps.png', width: 20) %>
        <% end %>
        <%= simple_format(@program.address.split("\n", 2)[1], { class: 'd-inline-flex ml-2' }) %>
      </div>
      <div class="card-body ">
        <div class="row">
          <div class="col-md-12">
            <table class="table">
              <tbody>
              <tr>
                <td class="font-weight-bold">
                  <%= t(:program_id) %>:
                </td>
                <td>
                  <div id="textToCopy" class="d-inline-block">
                    <%= @program.acgme_program_code %>
                  </div>
                  <div onclick="copyClipboard()" class="text-primary d-inline-block">[Copy]</div>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-sound-wave text-danger mr-2"></i>
                  <%= t(:speciality) %>
                </td>
                <td>
                  <%= @program.speciality.name %>
                </td>
              </tr>
              <tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-success mr-2"></i>
                  <%= t(:minimum_step_1) %>
                </td>
                <td>
                  <%= @program.minimum_step_1_score %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-info mr-2"></i>
                  <%= t(:requires_step_2_ck_completion) %>
                </td>
                <td>
                  <%= @program.step_2_required %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-warning mr-2"></i>
                  <%= t(:minimum_step_2_ck) %>
                </td>
                <td>
                  <%= @program.minimum_step_2_score %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-danger mr-2"></i>
                  <%= t(:require_step_2_cs_pass) %>
                </td>
                <td>
                  <%= @program.must_pass_step_2_cs_first_attempt %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-world-2 text-success mr-2"></i>
                  <%= t(:visa_types_sponsored) %>
                </td>
                <td>
                  <%= @program.visa_types_sponsored_display %>
                </td>
              </tr>
              <% unless @program.us_clinical_experience.nil? %>
                <tr>
                  <td>
                    <i class="nc-icon nc-badge text-primary mr-2"></i>
                    <%= t(:requires_us_clinical_experience) %>
                  </td>
                  <td>
                    <%= @program.us_clinical_experience ? 'Yes' : 'No' %>
                  </td>
                </tr>
              <% end %>
              <% unless @program.years_since_graduation.nil? %>
                <tr>
                  <td>
                    <i class="nc-icon nc-hat-3 text-warning mr-2"></i>
                    <%= t(:maximum_years_since_graduation) %>
                  </td>
                  <td>
                    <%= @program.years_since_graduation %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="card-footer ">
        <div class="stats text-right">
          <i class="fa fa-history"></i> Updated <%= @program.updated_at.strftime("%B %d, %Y") %>
        </div>
      </div>
    </div>
    <% if @program.medical_schools.present? %>
      <div class="row">
        <div class="col-md-12">
          <div class="card ">
            <div class="card-header ">
              <h5 class="card-title text-uppercase font-weight-bold"><%= t(:top_feeder_medical_schools) %></h5>
            </div>
            <div class="card-body ">
              <div class="row">
                <div class="col-md-12">
                  <table class="table">
                    <tbody>
                    <tr>
                      <td>
                        <% @program.medical_schools.order(percentage: :desc).limit(5).each.with_index(1) do |medical_school| %>
                          <li><%= medical_school.name %></li>
                        <% end %>
                      </td>
                    </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <% unless current_user.nil? %>
      <div class="row">
        <div class="col-md-12">
          <div class="card ">
            <div class="card-header ">
              <h5 class="card-title"><%= t(:notes) %></h5>
            </div>
            <div class="card-body ">
              <div class="row">
                <div class="col-md-12">
                  <% if can? :edit, @program %>
                    <%= link_to '', class: 'btn btn-light border' do %>
                      <i class="ti-pencil"> </i><%= t(:edit) %>
                    <% end %>
                  <% end %>

                  <%= bootstrap_form_for @form, :url => speciality_program_note_url(@speciality, @program), control_col: 'col-md-12', :method => :post do |f| %>
                    <div class="field">
                      <%= f.text_area :note, hide_label: true, rows: 5 %>
                    </div>

                    <div class="actions text-right">
                      <%= f.submit t(:save), class: 'btn btn-info' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-4">
    <% unless current_user.nil? %>
      <div class="text-center mb-4">
        <% if current_user.admin? %>
          <%= link_to edit_speciality_program_url(@speciality, @program), class: 'text-decoration-none' do %>
            <button type="button" class="btn btn-lg btn-block"><%= t(:edit_program) %></button>
          <% end %>
        <% end %>

        <%= link_to speciality_program_bookmark_url(@speciality, @program), class: 'text-decoration-none', method: :post do %>
          <% if @program.bookmarked?(current_user) %>
            <button type="button" class="btn btn-lg btn-danger btn-block"><%= t(:remove_program) %></button>
          <% else %>
            <button type="button" class="btn btn-lg btn-info btn-block"><%= t(:bookmark_program) %></button>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @program.friendliness_data? %>
      <div class="card <%= 'border-success' if current_user.nil? %>">
        <div class="card-header ">
          <h5 class="card-title text-uppercase font-weight-bold"><%= t(:friendliness_score) %></h5>
        </div>
        <div class="card-body ">
          <div class="row">
            <div class="col-md-12">
              <div class="small text-muted mb-3"><%= t(:friendliness_score_help_text_html) %></div>

              <table class="table">
                <tbody>
                <% %i[us_md_graduates us_do_graduates non_us_citizen_international_medical_graduates us_citizen_international_medical_graduates].each do |attribute| %>
                  <tr>
                    <td>
                      <%= t(attribute, scope: :img_types) %>
                    </td>
                    <td class="font-weight-bold">
                      <%= @program.send("#{attribute}_friendliness_score") %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
              <% if current_user.nil? %>
                <%= link_to 'View Programs Matching My Profile', root_path, class: 'btn btn-lg btn-success text-white'  %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <% if current_user.nil? %>
        <%= link_to 'View Programs Matching My Profile', root_path, class: 'btn btn-lg btn-success text-white'  %>
      <% end %>
    <% end %>

    <div class="card">
      <div class="card-header ">
        <h5 class="card-title text-uppercase font-weight-bold"><%= t(:contact_details) %></h5>
      </div>
      <div class="card-body ">
        <% unless current_user.nil? %>
          <label><%= t(:email) %>: </label>
          <span><%= mail_to @program.email %></span><br/>
        <% end %>

        <label><%= t(:program_coordinator) %>: </label>
        <span><%= @program.program_coordinator %></span><br/>

        <% unless current_user.nil? %>
          <label><%= t(:program_coordinator_email) %>: </label>
          <span><%= mail_to @program.program_coordinator_email %></span><br/>
        <% end %>

        <label><%= t(:program_director) %>: </label>
        <span><%= @program.program_director %></span><br/>

        <% unless current_user.nil? %>
          <label><%= t(:phone) %>: </label>
          <span><%= @program.phone %></span><br/><br/>
        <% end %>

        <% unless current_user.nil? %>
          <label><%= t(:website) %>:</label>
          <%= link_to(@program.website, @program.website, target: :_blank) %>
        <% end %>
      </div>
    </div>
  </div>
</div>