config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  authenticated :user do
    root :to => "dashboard#show", as: :authenticated_root
  end

  root :to => 'registration#show', id: 'profile'

  resources :specialities do
    resources :download_programs
    resources :programs do
      resource :bookmark
      resource :note
    end
  end

  resource :contact
  resources :registration
  resources :users

  get '/sitemap.xml', to: 'sitemap#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable

  has_many :visits, class_name: 'Ahoy::Visit', dependent: :destroy
  has_many :events, through: :visits, dependent: :destroy

  validates_presence_of :step_1_score, :img_type, :years_since_graduation, :visa
  validates_inclusion_of :step_1_score, in: 1..300, message: I18n.t(:invalid_score_error)
  validates_inclusion_of :step_2ck_score, in: 1..300, allow_nil: true,
                                          message: I18n.t(:invalid_score_error)
  validates_inclusion_of :us_clinical_experience, in: [true, false]
  validates_inclusion_of :passed_step_2cs_first_attempt, in: [true, false]
  validates_uniqueness_of :email, conditions: -> { where.not(email: '') }

  enum img_type: { us_md_graduates: 0,
                   non_us_citizen_international_medical_graduates: 1,
                   us_citizen_international_medical_graduates: 2,
                   us_do_graduates: 3 }

  enum visa: { no: 0,
               j_1_sponsorship_through_ecfmg: 1,
               h1_b: 2,
               j1_or_h1: 3 }

  def caribbean_img?
    img_type == 'us_citizen_international_medical_graduates'
  end

  def non_caribbean_img?
    img_type == 'non_us_citizen_international_medical_graduates'
  end

  def img?
    caribbean_img? || non_caribbean_img?
  end

  def attempts_to_upgrade
    events.select { |event| event.name == 'User attempted to upgrade' }
  end

  def friendliness_threshold
    if step_2ck_score.present?
      (100 - (((step_1_score + step_2ck_score) / 2).fdiv(280) * 100)).floor
    else
      (100 - (step_1_score.fdiv(280) * 100)).floor
    end
  end

  protected

  def password_required?
    false
  end

  def email_required?
    false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_paid_user, except: %i[index show]
  load_and_authorize_resource :user, only: %i[show destroy]

  def show
    @user = @user.decorate
  end

  def index
    @users = User.includes(:visits, :events)
                 .where.not(email: '')
                 .order(created_at: :desc)

    @users = @users.decorate
  end

  def edit
    @form = EditUserForm.new user: current_user
  end

  def update
    @form = edit_form(current_user, @current_ability)

    if @form.submit
      ahoy.track('User updated profile')

      flash.notice = 'User profile edited successfully'
      redirect_to root_path
    else
      ahoy.track('User failed to update profile')

      flash.alert = @form.display_errors
      redirect_to edit_user_path
    end
  end

  def destroy
    if @user.destroy
      flash.notice = 'User successfully deleted'
      redirect_to users_path
    else
      render 'show'
    end
  end

  private

  def edit_form(user, ability)
    form_params = params.require(:edit_user_form).permit(EditUserForm.accessible_attributes)
    EditUserForm.new form_params.merge(user: user, ability: ability)
  end

  def redirect_paid_user
    redirect_to root_path unless current_ability.edit_profile?
  end
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card ">
      <div class="card-header ">
        <h4 class="card-title font-weight-bold"><%= t(:edit_profile) %></h4>
      </div>

      <div class="card-body mt-3">
        <div class="row">
          <div class="col-md-12">
            <%= bootstrap_form_for @form, :url => user_url, label_col: 'col-sm-3', control_col: 'col-sm-5', method: :put do |f| %>
              <div class="field">
                <%= f.select :img_type,
                             options_for_select(User.img_types.keys.map { |p| [t(p, scope: :img_types), p] },
                                                selected: @form.img_type),
                             label_class: 'required',
                             label: t(:applicant_type) %>
              </div>

              <div class="field">
                <%= f.text_field :step_1_score, help: t(:valid_score_help_text), label_class: 'required' %>
              </div>

              <div class="field">
                <%= f.text_field :step_2ck_score, label: t(:step_2_ck_score), help: t(:valid_score_help_text) %>
              </div>

              <div class="field">
                <%= f.select :passed_step_2cs_first_attempt, [['Yes', true], ['No', false]], label: t(:passed_step_2cs_first_attempt), :label_class => 'required' %>
              </div>

              <div class="field">
                <%= f.select :us_clinical_experience, [['Yes', true], ['No', false]], label_class: 'required', label: t(:us_clinical_experience) %>
              </div>

              <div class="field">
                <%= f.select :visa, options_for_select(User.visas.keys.map { |p| [t(p, scope: :visa_types), p] }, selected: @form.visa), label: t(:visa_required), label_class: 'required' %>
              </div>

              <div class="field">
                <%= f.select :years_since_graduation, options_for_select(0..10, :selected => @form.years_since_graduation), label_class: 'required' %>
              </div>

              <div class="actions">
                <%= f.submit t(:save), class: 'btn btn-success' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-12 col-md-6 col-sm-12">
    <div class="card">
      <div class="card-header d-flex">
        <div class="float-left">
          <h4 class="card-title font-weight-bold">
            <%= t(:admin, scope: :sidebar) %>
          </h4>
        </div>
      </div>

      <div class="card-body ">
        <div class="row">
          <div class="col-md-12">
            <table class="table table-hover">
              <thead>
              <tr>
                <th><%= t(:full_name) %></th>
                <th><%= t(:email) %></th>
                <th><%= t(:visitor_count, scope: :admin) %></th>
                <th><%= t(:attempts_to_upgrade, scope: :admin) %></th>
                <th><%= t(:created_at) %></th>
                <th><%= t(:last_sign_in_at) %></th>
              </tr>
              </thead>
              <tbody>
                <% @users.each do |user| %>
                  <tr class="<%= 'table-success' if user.paid? %>">
                    <td><%= link_to(user.full_name_display, user_path(user)) %></td>
                    <td><%= user.email %></td>
                    <td><%= user.visits.size %></td>
                    <td><%= user.attempts_to_upgrade.size %></td>
                    <td><%= user.created_at_display %></td>
                    <td><%= user.last_sign_in_at_display %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-12 col-md-6 col-sm-12">
    <div class="card">
      <div class="card-header d-flex">
        <div class="float-left">
          <h4 class="card-title font-weight-bold"><%= @user.full_name_display %></h4>
          <div class="mb-3"><%= @user.email %></div>
        </div>
        <div class="ml-auto align-self-center">
          <%= link_to user_path, method: :delete, remote: true do %>
            <button type="button" class="btn btn-sm btn-danger"><%= t(:delete) %></button>
        <% end %>
        </div>

      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-12">
            <table class="table">
              <tbody>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-success mr-2"></i>
                  <%= t(:applicant_type, scope: :admin) %>
                </td>
                <td>
                  <%= @user.applicant_type_display %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-success mr-2"></i>
                  <%= t(:step_1_score, scope: :admin) %>
                </td>
                <td>
                  <%= @user.step_1_score %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-warning mr-2"></i>
                  <%= t(:step_2_ck_score, scope: :admin) %>
                </td>
                <td>
                  <%= @user.step_2ck_score %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-chart-bar-32 text-danger mr-2"></i>
                  <%= t(:step_2_cs_pass_first_attempt, scope: :admin) %>
                </td>
                <td>
                  <%= @user.passed_step_2cs_first_attempt_display %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-world-2 text-success mr-2"></i>
                  <%= t(:visa_required, scope: :admin) %>
                </td>
                <td>
                  <%= @user.visa_display %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-badge text-primary mr-2"></i>
                  <%= t(:us_clinical_experience, scope: :admin) %>
                </td>
                <td>
                  <%= @user.us_clinical_experience_display %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="nc-icon nc-hat-3 text-warning mr-2"></i>
                  <%= t(:years_since_graduation, scope: :admin) %>
                </td>
                <td>
                  <%= @user.years_since_graduation %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="fa fa-dollar mr-2"></i>
                  <%= t(:paid, scope: :admin) %>
                </td>
                <td>
                  <%= @user.paid_display %>
                </td>
              </tr>
              <tr>
                <td>
                  <i class="fa fa-cc-stripe mr-2"></i>
                  <%= t(:attempts_to_upgrade, scope: :admin) %>
                </td>
                <td>
                  <%= @user.attempts_to_upgrade.size %>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <% @user.visits.reverse.each do |visit| %>
      <div class="card">
          <div class="card-header d-flex pb-3">
            <div class="float-left">
              <h4 class="card-title font-weight-bold">
                <%= visit.started_at.in_time_zone('Pacific Time (US & Canada)').strftime("%b %e %Y") %>
              </h4>
              <div><label class="text-muted">IP Address:&nbsp;</label><%= visit.ip %></div>
              <div><label class="text-muted">Platform:&nbsp;</label><%= visit.browser %> on <%= @user.visits.last.device_type %> (<%= @user.visits.last.os %>)</div>
              <div><label class="text-muted">Referrer:&nbsp;</label><%= link_to(visit.referrer, visit.referrer, target: :_blank) %></div>
              <div><label class="text-muted">Destination:&nbsp;</label><%= link_to(visit.landing_page, visit.landing_page, target: :_blank) %></div>
            </div>
          </div>

          <div class="card-body ">
            <div class="row">
                <div class="col-md-12">
                  <table class="table table-hover">
                    <thead>
                    <tr>
                      <th><%= t(:event, scope: :admin) %></th>
                      <th><%= t(:time, scope: :admin) %></th>
                    </tr>
                    </thead>

                    <tbody>
                      <% visit.events.each do |event| %>
                        <tr>
                          <td><%= event.name %></td>
                          <td><%= event.time.in_time_zone('Pacific Time (US & Canada)').strftime("%r") %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>